import { createClient } from '@supabase/supabase-js';
import { projectId, publicAnonKey as defaultAnonKey } from '/utils/supabase/info';

// Use environment variables if available, otherwise fall back to the autogenerated info
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || defaultAnonKey;

// Create Supabase client singleton
export const supabase = createClient(supabaseUrl, publicAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});

// Helper function to call Edge Functions
export async function callEdgeFunction<T = any>(
  functionName: string,
  body?: any,
  accessToken?: string
): Promise<{ data: T | null; error: any }> {
  try {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };

    // Use access token if provided (for authenticated requests)
    // Otherwise use the public anon key
    if (accessToken) {
      headers['Authorization'] = `Bearer ${accessToken}`;
    } else {
      headers['Authorization'] = `Bearer ${publicAnonKey}`;
    }

    const response = await fetch(
      `${supabaseUrl}/functions/v1/make-server-7456b3bc/${functionName}`,
      {
        method: 'POST',
        headers,
        body: body ? JSON.stringify(body) : undefined,
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      return { data: null, error: new Error(errorText || response.statusText) };
    }

    const data = await response.json();
    return { data, error: null };
  } catch (error) {
    console.error(`Edge function ${functionName} error:`, error);
    return { data: null, error };
  }
}
